version: "3.10"

services:
  alice_chatgpt:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: alice_chatgpt
    image: alice_chatgpt_image
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      OAI_TOKEN: ${OAI_TOKEN}
      ALICE_TOKEN: ${ALICE_TOKEN}

networks:
  deml:
    name: "deml"