version: "3.10"

services:

  alice_chatgpt:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: alice_chatgpt
    image: alice_chatgpt_image
    restart: always
    environment:
      OAI_TOKEN: $OAI_TOKEN
      ALICE_TOKEN: $ALICE_TOKEN
    expose:
      - 8321
    networks:
      - deml

networks:
  deml:
    name: "deml"